
import React from 'react';
import { Layers, KanbanSquare, ArrowRight, LayoutDashboard, Shield, Table, CalendarDays, Zap, CheckCircle2 } from 'lucide-react';

interface LandingPageProps {
  onLoginClick: () => void;
}

const AppMockup: React.FC = () => (
    <div className="relative mt-2 max-w-8xl mx-auto">
        <div className="absolute -inset-x-8 -inset-y-4 bg-gradient-to-r from-brand-600/20 to-purple-600/20 rounded-3xl blur-2xl opacity-50"></div>
        <div className="relative bg-slate-800/50 backdrop-blur-xl border border-white/10 rounded-2xl shadow-2xl p-4 ring-1 ring-inset ring-white/10">
            <div className="flex justify-between items-center mb-3 px-2">
                <div className="flex items-center gap-2">
                    <span className="w-3 h-3 bg-red-500 rounded-full"></span>
                    <span className="w-3 h-3 bg-yellow-500 rounded-full"></span>
                    <span className="w-3 h-3 bg-green-500 rounded-full"></span>
                </div>
                <div className="w-1/2 h-4 bg-slate-700/50 rounded-md"></div>
            </div>
            <div className="grid grid-cols-3 gap-3">
                <div className="space-y-2">
                    <div className="h-6 bg-slate-700/80 rounded-md flex items-center justify-center text-xs text-slate-400">To Do</div>
                    <div className="h-16 bg-slate-700/50 rounded-lg p-2"><div className="w-3/4 h-2 bg-slate-600/80 rounded-full"></div></div>
                    <div className="h-24 bg-slate-700/50 rounded-lg p-2"><div className="w-1/2 h-2 bg-slate-600/80 rounded-full"></div></div>
                </div>
                <div className="space-y-2">
                    <div className="h-6 bg-slate-700/80 rounded-md flex items-center justify-center text-xs text-slate-400">In Progress</div>
                    <div className="h-20 bg-slate-700/50 rounded-lg p-2"><div className="w-3/4 h-2 bg-slate-600/80 rounded-full"></div></div>
                    <div className="h-12 bg-slate-700/50 rounded-lg p-2"><div className="w-full h-2 bg-slate-600/80 rounded-full"></div></div>
                    <div className="h-16 bg-slate-700/50 rounded-lg p-2"><div className="w-1/2 h-2 bg-slate-600/80 rounded-full"></div></div>
                </div>
                <div className="space-y-2">
                    <div className="h-6 bg-slate-700/80 rounded-md flex items-center justify-center text-xs text-slate-400">Done</div>
                    <div className="h-16 bg-slate-700/50 rounded-lg p-2"><div className="w-3/4 h-2 bg-slate-600/80 rounded-full"></div></div>
                </div>
            </div>
        </div>
    </div>
);


export const LandingPage: React.FC<LandingPageProps> = ({ onLoginClick }) => {
  const features = [
    {
      icon: LayoutDashboard,
      title: 'Unified Command Center',
      description: 'Get an instant, real-time overview of your projects with an intelligent dashboard that displays progress, key metrics, activity highlights, and project-wide insights generated by AI.'
    },
    {
      icon: KanbanSquare,
      title: 'Smart & Dynamic Workspaces',
      description: 'Visualize tasks with Kanban boards, schedule work using Gantt timelines, and collaborate effortlessly with assignments, discussions, status tracking, and AI-suggested subtasks.'
    },
    {
      icon: Table,
      title: 'Insightful Data & Reporting',
      description: 'Use a spreadsheet-style view for fast bulk updates, integrated reporting, and AI-generated executive summaries that highlight risks, delays, and recommendations.'
    },
    {
      icon: Shield,
      title: 'Secure & Scalable Admin Controls',
      description: 'Manage teams confidently with role-based access, encrypted credentials, and a complete audit log tracking every change, action, and update across the system.'
    }
  ];

  return (
    <div className="bg-slate-900 text-white min-h-screen font-sans selection:bg-brand-500/30 overflow-x-hidden flex flex-col">
      <div className="absolute top-0 left-0 w-full h-full overflow-hidden z-0 pointer-events-none">
        <div className="absolute top-[-20%] left-[-20%] w-1/2 h-1/2 bg-purple-600/20 rounded-full blur-[150px] animate-pulse"></div>
        <div className="absolute bottom-[-20%] right-[-20%] w-1/2 h-1/2 bg-brand-600/20 rounded-full blur-[150px] animate-pulse delay-1000"></div>
      </div>
      
      <div className="relative z-10 flex-1">
        {/* Header */}
        <header className="py-6 px-4 md:px-8 animate-in fade-in duration-500">
          <div className="max-w-7xl mx-auto flex justify-between items-center">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-slate-800 rounded-lg flex items-center justify-center border border-white/10">
                <Layers className="text-brand-400" />
              </div>
              <span className="text-xl font-bold">Task Flow</span>
            </div>
            <button
              onClick={onLoginClick}
              className="px-4 py-2 text-sm font-semibold bg-white/10 border border-white/20 rounded-lg backdrop-blur-sm hover:bg-white/20 transition-colors"
            >
              Sign In / Try Product
            </button>
          </div>
        </header>

        {/* Hero Section */}
        <main className="max-w-7xl mx-auto px-4 md:px-8">
          <section className="text-center pt-12 pb-16 md:pt-20 md:pb-20 relative">
            <h1 className="text-3xl md:text-5xl lg:text-6xl font-extrabold bg-gradient-to-b from-white via-slate-200 to-slate-500 bg-clip-text text-transparent leading-snug pb-4 animate-in fade-in slide-in-from-top-4 duration-700 tracking-tight mb-4 max-w-6xl mx-auto">
              Transform Your Project Management
            </h1>
            
            <p className="max-w-4xl mx-auto text-lg md:text-xl text-slate-400 leading-relaxed animate-in fade-in slide-in-from-top-4 duration-700 delay-200 mb-20">
              Task Flow is an AI-powered project management platform that helps teams <span className="text-slate-100 font-medium">plan better</span>, <span className="text-slate-100 font-medium">collaborate faster</span>, and <span className="text-slate-100 font-medium">deliver projects with confidence</span>. From intelligent task suggestions to real-time dashboards, everything you need is built into one seamless system.
            </p>
            <button
              onClick={onLoginClick}
              className="group relative px-8 py-4 bg-gradient-to-r from-brand-600 to-brand-500 text-white font-bold rounded-xl transition-all transform hover:scale-105 shadow-2xl shadow-brand-500/30 animate-in fade-in slide-in-from-top-4 duration-700 delay-300 hover:shadow-brand-500/50"
            >
              <span className="flex items-center gap-2 text-lg">
                Get Started for Free
                <ArrowRight className="group-hover:translate-x-1 transition-transform" />
              </span>
            </button>
            <p className="mt-4 mb-20 text-sm text-slate-500 animate-in fade-in slide-in-from-top-4 duration-700 delay-500">
              No credit card required.
            </p>
            
            <div className="animate-in fade-in zoom-in-95 duration-1000 delay-500">
                <AppMockup />
            </div>
          </section>

          {/* Workflow Section (Plan. Execute. Complete) */}
          <section className="mb-24 animate-in fade-in slide-in-from-bottom-8 duration-700 delay-200 mt-16">
             <div className="relative bg-slate-800/30 border border-white/10 rounded-3xl px-6 py-6 md:px-12 md:py-6 overflow-hidden backdrop-blur-sm shadow-xl">
                 <div className="absolute inset-0 bg-gradient-to-b from-brand-900/10 to-transparent pointer-events-none"></div>
                 
                 <div className="relative z-10">
                    <div className="text-center mb-6">
                      <h2 className="text-3xl md:text-5xl font-bold bg-gradient-to-r from-brand-300 via-white to-purple-300 bg-clip-text text-transparent mb-3 pb-1">
                          Plan. Execute. Complete. Smarter.
                      </h2>
                      <p className="text-slate-400 text-lg max-w-2xl mx-auto">
                        Task Flow merges powerful AI automation with modern project management tools, giving you clarity, speed, and consistency.
                      </p>
                      <p className="text-slate-400 text-lg max-w-2xl mx-auto">
                        ‎ ‎ 
                      </p>
                      <p className="text-slate-400 text-lg max-w-2xl mx-auto">
                        ‎ ‎ 
                      </p>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                        {/* Step 1 */}
                        <div className="bg-slate-900/50 border border-white/5 p-6 rounded-2xl hover:bg-slate-800/60 transition-all duration-300 group hover:-translate-y-1">
                            <div className="w-14 h-14 bg-blue-500/20 rounded-xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform duration-300 border border-blue-500/20">
                                <CalendarDays className="text-blue-400" size={28} />
                            </div>
                            <h3 className="text-xl font-bold text-white mb-2">1. Plan</h3>
                            <p className="text-slate-400 text-sm leading-relaxed">
                                Organize tasks, set smart deadlines, and assign roles effortlessly with AI-driven insights that help you start on the right foot.
                            </p>
                        </div>

                        {/* Step 2 */}
                        <div className="bg-slate-900/50 border border-white/5 p-6 rounded-2xl hover:bg-slate-800/60 transition-all duration-300 group hover:-translate-y-1">
                             <div className="w-14 h-14 bg-amber-500/20 rounded-xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform duration-300 border border-amber-500/20">
                                <Zap className="text-amber-400" size={28} />
                            </div>
                            <h3 className="text-xl font-bold text-white mb-2">2. Execute</h3>
                            <p className="text-slate-400 text-sm leading-relaxed">
                                Collaborate in real-time, track progress on dynamic Kanban boards, and keep your entire team aligned and moving forward.
                            </p>
                        </div>

                        {/* Step 3 */}
                        <div className="bg-slate-900/50 border border-white/5 p-6 rounded-2xl hover:bg-slate-800/60 transition-all duration-300 group hover:-translate-y-1">
                             <div className="w-14 h-14 bg-emerald-500/20 rounded-xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform duration-300 border border-emerald-500/20">
                                <CheckCircle2 className="text-emerald-400" size={28} />
                            </div>
                            <h3 className="text-xl font-bold text-white mb-2">3. Complete</h3>
                            <p className="text-slate-400 text-sm leading-relaxed">
                                Deliver on time with automated reporting, instant executive summaries, and clear audit trails that prove your success.
                            </p>
                        </div>
                    </div>
                 </div>
             </div>
          </section>
          
          {/* Features Grid Section */}
          <section className="pb-24 pt-12">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-bold animate-in fade-in duration-500 mb-4">All Your Project Needs in One Platform</h2>
              <p className="text-slate-400 max-w-2xl mx-auto">Everything you need to manage your work efficiently in one unified workspace.</p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
              {features.map((feature, index) => (
                <div 
                    key={index} 
                    className="bg-white/5 border border-white/10 rounded-2xl p-6 backdrop-blur-lg transform hover:-translate-y-2 transition-transform duration-300 animate-in fade-in slide-in-from-bottom-8 duration-700 hover:bg-white/10"
                    style={{ animationDelay: `${200 + index * 150}ms`, willChange: 'transform, opacity' }}
                >
                  <div className="w-12 h-12 bg-brand-500/10 border border-brand-500/20 rounded-xl flex items-center justify-center mb-4">
                    <feature.icon className="text-brand-400" size={24} />
                  </div>
                  <h3 className="font-bold text-lg mb-2">{feature.title}</h3>
                  <p className="text-sm text-slate-400 leading-relaxed">{feature.description}</p>
                </div>
              ))}
            </div>
          </section>
        </main>

        {/* Footer */}
        <footer className="py-12 border-t border-white/10 bg-black/20">
          <div className="max-w-7xl mx-auto px-4 md:px-8 text-center text-slate-500 text-sm">
            <p>&copy; 2025 Task Flow by M. Aliyan H. Qureshi. All rights reserved.</p>
          </div>
        </footer>
      </div>
    </div>
  );
};
